# Generated by Django 3.0.3 on 2020-08-02 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('desc', models.CharField(max_length=300)),
                ('price', models.DecimalField(decimal_places=2, max_digits=9)),
                ('category', models.CharField(default='vegetables', max_length=100)),
                ('p_date', models.DateField()),
                ('image', models.ImageField(upload_to='shop/images')),
            ],
        ),
        migrations.DeleteModel(
            name='Vegetables',
        ),
    ]
